# Generated by Django 3.1.4 on 2021-11-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=225)),
                ('lastName', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('dateOfBirth', models.DateField(max_length=225)),
                ('phoneNo', models.IntegerField()),
                ('emailAddress', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.country'),
        ),
    ]
