# Generated by Django 3.1.4 on 2021-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211106_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
