# Generated by Django 3.1.4 on 2021-11-07 13:07

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20211107_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to=task.models.upload_path),
        ),
    ]
